### PR TITLE
breadcrumb test for #198 plus open-type-ligature test fix

### PR DESCRIPTION
**Pull request by dbox**
This pulls in #198 and adds tests

### CODE REVIEW

**Comment by dbox** [comment]
failed tests whatttt

**Comment by dbox** [comment]
@jenius i think there is some difference in the local test and travis tests. for whatever reason the local one wanted  `-moz-font-feature-settings: "liga", "dlig";` added to open-type-ligatures.

**Comment by jenius** [comment]
hmm that is pretty strange. did you clear and reinstall all the deps locally too I assume?

**Comment by dbox** [comment]
remove `node_modules` and new `npm install` seems to have worked. I'll try to squash this up

**Comment by dbox** [comment]
Squashed up. Should be safe to merge this one and close #198

**Comment by jenius** [comment]
Whoo! Thanks :+1:

**Pull request merged**
