### PR TITLE
Fix #158: add missing hover-color case

### LINKED ISSUE #158: force-use-color parameter missing from hover-color() when @background-color
#33 introduced [an update to `hover-color()`](https://github.com/jenius/axis/pull/33/files#diff-e1df0bae22a6c7dbf7845dc049c10498R81) that I think is missing the `force-use-color` parameter.

When I have a style such as:
```styl
li {
    background-color transparent // or initial, to reset a background-color from above
    hover-color red true
}
```

The result is a list item whose background swaps to red on hover, rather than respecting the second argument of true to `hover-color()`. Is this the intended behavior?

### PR DESCRIPTION
**Pull request by vevo-arthur-klepchukov**
#33 introduced an update to hover-color() that I think is missing the
force-use-color parameter.

When I have a style such as:

```styl
li {
  background-color transparent // or initial, to reset a background-color from above
  hover-color red true
}
```

The result is a list item whose background swaps to red on hover,
rather than respecting the second argument of true to hover-color().

Adding a force-use-color check fixes this.

### CODE REVIEW

**Comment by jenius** [comment]
This looks good. The test failures seems like a dependency update to me, I'm going to make sure they are passing then merge this. Thanks so much for the contribution!

**Comment by vevo-arthur-klepchukov** [comment]
Thanks. Yeah, I couldn't get npm test to succeed even with a fresh clone of the repo.

**Comment by jenius** [comment]
Hey @vevo-arthur-klepchukov -- just fixed the issue, sorry about that. Could you just rebase this on top of master then we'll merge?

**Comment by vevo-arthur-klepchukov** [comment]
Tests now pass :)

**Comment by jenius** [comment]
Perfect. Thanks for the contribution @vevo-arthur-klepchukov!

**Pull request merged**
