### PR TITLE
Remove Nib

### PR DESCRIPTION
**Pull request by jenius**
Ref #192 

Not yet complete, but the majority of the work has been done here and tests are passing. Still needs touchups, a couple more tools imported from nib, and some adjustments to the visual test results.

We also need a summary of all the breaking changes somewhere, which is going to be rather large.

On the plus side, the code is significantly lighter, cleaner, and better. Whoo! :tada:

### CODE REVIEW

**Comment by dbox** [comment]
Wow rad. Wide just had a baby, so will follow up soonish.

**Comment by declandewet** [comment]
congrats @dbox :) :baby: :baby_bottle: 

Nice work, @jenius

**Comment by jenius** [comment]
Woah, congrats man! This is amazing! :tada: :baby: 

You gotta post a photo in this issue thread, it will be amazing

**Comment by dbox** [comment]
image

Elliott

**Comment by jenius** [comment]
Best PR discussion ever. Congrats again, this is the cutest baby! My girlfriend would like me to also let you know that "Elliott is a cutie bear".

:baby:

**Comment by kylemac** [comment]
This is great stuff

**Comment by kylemac** [comment]
The baby, that is. the PR IS JUNK.

**Comment by dbox** [comment]
Okay, renamed him to Axis Stylus Border Box.

**Comment by hhsnopek** [comment]
Congratz @dbox ! :baby:

**Comment by dbox** [comment]
Thanks everyone. We're home now and I have him learning some basic HTML markup, hopefully he'll be able to start pulling his weight on Axis soon.

@jenius This PR is incred and i'm super stoked on it.

**Comment by jenius** [comment]
At very least his middle name should be axis

**Comment by dbox** [comment]
Wow, tests run way faster now for me now.

>  Still needs touchups, a couple more tools imported from nib, and some adjustments to the visual test results.

Let me know what you want help with @jenius.

**Comment by dbox** [comment]
Okay, added `global-reset`,`shadow-stroke`, `ellipsis` and cleaned up a few things. Only thing I see missing from our original list is nib's border-radius. I could probably figure it out but not dying for it...

**Comment by jenius** [comment]
Great, all these changes look good. I'll pull down and take another sweep of this soon!

**Comment by jenius** [comment]
Ok sorry for the delay, I'm going to take another pass on this in the next couple of days and try to get this merged up. Whoo! :tada:

**Comment by jenius** [comment]
Ok I'm feeling good about this. All tests passing, visual tests look good. Anyone want to take a final look at this before we merge up? cc @declandewet @dbox 

Also, we need a description of what changes were made here. I'm going to start working on this right now.

**Comment by jenius** [comment]
##### Changelog

In this release, we removed nib as a dependency. Why? First, nib is unmaintained, with enormous numbers of open issues and ignored pull requests. And second, nib still includes extra code for older browsers, code that is now very outdated and adds a bunch of unnecessary weight to the output. This capability is much better handled by [autoprefixer](https://github.com/postcss/autoprefixer).

As such, axis now ships with zero cross-browser support. It produces only bare minimum css3 spec compliant code. You can and should use [autoprefixer](https://github.com/postcss/autoprefixer) to ensure that your code works correctly across the range of browsers you need it to work with.

We did re-implement a number of the useful functions from nib, including:

- `global-reset` and all it's nested pieces
- position mixins (`absolute`, `relative`, and `fixed`)
- `clearfix` (although we recommend `group` instead)
- `overflow: ellipsis`

The only pieces from nib that were not included are:
- `image` (any reason we did not include this one guys?)
- `border-radius` (not judged to be frequently used)
- `gradients` (now just use css3 spec gradients and autoprefixer)
- all vendor prefixes properties

This is a large breaking change, hence the minor version bump (see [our pre-1.0 versioning policy](http://markup.im/#q4_cRZ1Q)). Use caution before running this upgrade on a live site, and if you do make sure to thoroughly check all pages and ensure they are still looking good.

**Comment by dbox** [comment]
Yay! I can't dive into this tonight (sleep is so precious right now), but this looks awesome. 

I say we just plaster warnings all over the release and go for it. Going to be hard to truly see what all breaks until we pull it into a live site. (Clearly we can start with axis-www.) 

I will have several updates ready to go as soon as this version ships, so I'll be available to quickly help patch anything that may need fixing. 

 Thanks for pulling it all together @jenius! I <3 Axis.

**Comment by dbox** [comment]
Okay, I did find one more reference to nib: readme.md.

**Comment by jenius** [comment]
Agreed. Updated the readme too.

Ok, so I'm about to ship this out. Whoo! :tada: That being said, we do have a decent amount of work to do once this has shipped. Mostly in updates to axis-www. I'll get started on this today, of course would appreciate any help, but I know you are in :baby: town, so don't even think about taking any time to do this unless you are relaxed and well-rested :grinning:

**Comment by jenius** [comment]
Published as `axis@0.5.0` :tada:

**Comment by dbox** [comment]
Whooo! Awesome! I'll be able to help on axis-www. Traveling this week too,
but I'll squeeze in some time.

**Pull request merged**
