### PR TITLE
Material design 'swift-out' easing added

### PR DESCRIPTION
**Pull request by FranzSkuffka**
Forked from James Delaney
http://codepen.io/jamesdelaneyie/pen/yidkA

### CODE REVIEW

**Comment by jenius** [comment]
Could you add the other variants as well? swift-in and swift-in-out as in the other easing formulas?

**Comment by FranzSkuffka** [comment]
I think swift-out is kind of the "trademark" easing. There are easings for elements leaving or entering the frame though, so i will add these.

**Comment by FranzSkuffka** [comment]
Does this meet the requirements now?

**Comment by FranzSkuffka** [comment]
Done.

**Comment by jenius** [comment]
Ok we're almost there! Last step is to squash all these commit together, so that when merged we get a nice clean history. In following with [the other commits in the history](https://github.com/jenius/axis/commits/master), it's best to use present imperative tense for the commit, for example "add material design swift easing".

After this I'll get it merged and shipped out!

**Comment by FranzSkuffka** [comment]
did a rebase aswell.

**Comment by jenius** [comment]
Perfect! Great work :tada:

**Comment by jenius** [comment]
One more thing, would you mind adding it to the axis docs site? https://github.com/jenius/axis-www/blob/master/views/index.jade#L124

**Pull request merged**
