### PR TITLE
Mixins

### PR DESCRIPTION
**Pull request by abstracthat**
Here's the mixins we discussed previously. Sorry it took a little while, I've been swamped.

- `border-box-html()`
- `fluid-media()`
- `ratio-box()`
- `print-styles()`

### CODE REVIEW

**Comment by dbox** [comment]
:+1:

**Comment by jenius** [comment]
Fantastic, thanks so much @abstracthat! This is great. Is there any chance you'd be willing to add examples of this to [axis-www](https://github.com/jenius/axis-www) when you have a moment?

**Comment by dbox** [comment]
If you don't want to @abstracthat I can. I have to add several things anyway.

@jenius I assume we need a new build released before I can add to axis-www. I'm happy to do, just need to know how you want to version it. Should we go 0.4.0?

**Comment by jenius** [comment]
Sounds good. Yeah, do you want to try cutting the release now that you are on core? Here's my general process --

1. Run `npm version x.x.x` with whatever version you want to go to. This will push a commit upping the package.json number and a git tag.
2. Run `git push && git push --tags` to push the version bump commit and the tag to github
3. In the releases tab, add the release notes and info
4. Run `npm publish .` to publish to npm
5. :tada: :confetti_ball:

**Comment by dbox** [comment]
Sounds easy enough. Will do. Bear with me if I make any mistakes. :)

**Comment by dbox** [comment]
Everything was smooth until step 4 which gave me this:

https://www.dropbox.com/s/qmjserq4ulbo6li/Screenshot%202015-06-04%2009.56.16.png?dl=0

Is this a permissions thing?

**Comment by jenius** [comment]
Yup sorry my bad. Just added you, try again!

**Comment by dbox** [comment]
Bingo! We're at 0.4.0. Go team!

I'll do the site updates this weekend. @abstracthat Just let me know if you want me to add your stuff. Happy to do, or if you want to, totally fine too.

**Comment by jenius** [comment]
My man! :hand:

**Comment by hhsnopek** [comment]
:confetti_ball: Yay!

**Comment by abstracthat** [comment]
I added a PR for these mixins and also bumped the axis version in axis-www. Thanks for getting this stuff out there guys!

**Pull request merged**
