### PR TITLE
Misc cleanup

### PR DESCRIPTION
**Pull request by dbox**
addresses #243, #255, & #261

### CODE REVIEW

**Comment by jenius** [comment]
lgtm :+1:

**Comment by dbox** [comment]
You want me to version up and publish?

**Comment by jenius** [comment]
yeah! make the magic happen :sparkles:

**Comment by dbox** [comment]
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "approvals/lgtm" is expected
To https://github.com/jenius/axis.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/jenius/axis.git'
```
looks like the LGTM is blocking me from doing so

**Comment by jenius** [comment]
haha god damn I honestly have no idea how to get rid of that service it's so annoying

**Comment by dbox** [comment]
I thought you set it up to keep the reigns on me!

**Comment by jenius** [comment]
Haha not at all, just wanted to test it out. But it totally doesn't work. I think I just turned it off, try again?

**Comment by dbox** [comment]
same error

**Comment by jenius** [comment]
:angry:

**Comment by dbox** [comment]
slack-imgs com

**Comment by jenius** [comment]
Ok I think I really got it this time. One more shot?

**Comment by dbox** [comment]
bingo :tada:

**Pull request merged**
