### PR TITLE
Add basic trigonometry using taylor series.

### PR DESCRIPTION
**Pull request by wkf**
For all those times you wanted to set the size of an element to sin(10). But seriously, I did actually use this combined with calc to properly size some elements that had been skewed (or rotated). YMMV.

### CODE REVIEW

**Comment by markalfred** [comment]
💁 #neverforget

**Comment by samccone** [comment]
🌮 🌀

**Comment by jescalan** [comment]
🐫

**Comment by wkf** [comment]
😭

**Pull request closed without merging**
