### PR TITLE
transition overriding nib

### PR DESCRIPTION
**Pull request by nickhudkins**
Nib's vendorizing gets broken since transition gets redefined here. Cache nibs 'transition' and then call it within your newly defined transition mixin :)

### CODE REVIEW

**Comment by jenius** [comment]
Does nib still vendorize things? I really need to drop nib as a dependency -______-

Thank you though, this is a solid patch. I'll ship this out soon!

**Comment by jenius** [comment]
Actually could you make sure the tests are updated to work before we merge?

**Comment by nickhudkins** [comment]
Absolutely :)

**Comment by nickhudkins** [comment]
Tests passing (locally) travis is taking his sweet time, commits squashed :+1:

**Comment by jenius** [comment]
Perfect, thanks Nick! This looks great. Really appreciate the contribution, and hope you are enoying axis!

**Pull request merged**
