### PR TITLE
UI: Range Slider per #108 (with passing tests)

### PR DESCRIPTION
**Pull request by dbox**
rewrote this to be more cross browser friendly.

http://codepen.io/dbox/pen/MwyKZm?editors=110

### CODE REVIEW

**Comment by jenius** [comment]
Beautiful. Really nice work. Thanks so much Dan!

**Comment by jenius** [comment]
Interested in adding these examples to [axis-www](https://github.com/jenius/axis-www) as well?

**Comment by dbox** [comment]
Definitely. Do you need to push a version-up before I can do that?

**Comment by dbox** [comment]
ping! (I know you're traveling but i'll need version up before i can add to axis-www. In the meantime i got my feet wet and have a nice PR waiting for you over there)

**Pull request merged**
